export const ORDER_FETCH_START = 'order/FETCH_START';
export const ORDER_FETCH_SUCCESS = 'order/FETCH_SUCCESS';
export const ORDER_FETCH_ERROR = 'order/FETCH_ERROR';

export const ORDERS_HISTORY_FETCH_START = 'orders/HISTORY_FETCH_START';
export const ORDERS_HISTORY_FETCH_SUCCESS = 'orders/HISTORY_FETCH_SUCCESS';
export const ORDERS_HISTORY_FETCH_ERROR = 'orders/HISTORY_FETCH_ERROR';